services:
  frontend:
    build:
      context: ./todo-frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        API_URL: ${API_URL}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL: ${API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-backend
      args:
        ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
        SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
        DB_ECHO_LOG: ${DB_ECHO_LOG}
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
      DB_ECHO_LOG: ${DB_ECHO_LOG}
      DB_PORT: 5432
