name: Deploy to Azure VM
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./todo-frontend
          push: true
          tags: |
            ghcr.io/hc-organizations/todo-frontend:latest

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./todo-backend
          push: true
          tags: |
            ghcr.io/hc-organizations/todo-backend:latest

      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: |
            GHCR_PAT=${{ secrets.GHCR_PAT }}
          script: |
            # 1) 리포지터리 준비
            REPO=git@github.com:hc-organizations/deploy-repo.git
            DIR=~/deploy
            if [ ! -d "$DIR/.git" ]; then
              git clone "$REPO" "$DIR"
            fi
            cd "$DIR"
            git pull origin main

            # 2) GHCR 로그인
            echo "$GHCR_PAT" | docker login ghcr.io \
              -u ${{ github.actor }} --password-stdin

            # 3) 환경변수 export
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

            # 4) 배포
            docker compose pull
            docker compose up -d --no-build
