name: Deploy to Azure VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # 2) 디렉터리 준비
            mkdir -p ~/deploy
            cd ~/deploy

            # 3) 배포 레포 (docker-compose.yml) 클론 또는 pull
            if [ ! -f docker-compose.yml ]; then
              git clone https://github.com/hc-organizations/todo-deploy.git .
            else
              git pull origin main
            fi

            # 4) Frontend 소스 클론 또는 pull
            if [ ! -d todo-frontend ]; then
              git clone https://github.com/hc-organizations/todo-frontend.git todo-frontend
            else
              cd todo-frontend && git pull origin main && cd ..
            fi

            # 5) Backend 소스 클론 또는 pull
            if [ ! -d todo-backend ]; then
              git clone https://github.com/hc-organizations/todo-backend.git todo-backend
            else
              cd todo-backend && git pull origin main && cd ..
            fi

            # 6) 환경변수 파일(.env) 생성
            cat > .env <<EOF
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            API_URL=${{ secrets.API_URL }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            ASYNC_DATABASE_URL=${{ secrets.ASYNC_DATABASE_URL }}
            SYNC_DATABASE_URL=${{ secrets.SYNC_DATABASE_URL }}
            DB_ECHO_LOG=${{ secrets.DB_ECHO_LOG }}
            EOF

            # 7) Docker Compose로 이미지 빌드 & 배포
            sudo docker compose up -d --build
