name: Deploy to Azure VM
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) 배포용 레포(Compose 파일 등) 체크아웃 — Runner
      - uses: actions/checkout@v4
        with:
          path: deploy

      # (… frontend/backend 체크아웃, 빌드&푸시 생략 …)

      # 7) VM에 SSH 배포
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: |
            GHCR_PAT=${{ secrets.GHCR_PAT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
        script: |
          # 0) git 설치 (Ubuntu 예시)
          sudo apt-get update
          sudo apt-get install -y git

          # 1) 배포 디렉터리 준비
          mkdir -p ~/deploy
          cd ~/deploy

          # 2) repo clone or pull
          if [ ! -d ".git" ]; then
            git clone https://github.com/hc-organizations/deploy-repo.git .
          else
            git pull origin main
          fi

          # 3) GHCR 로그인 (non‑TTY)
          echo "$GHCR_PAT" \
            | docker login ghcr.io \
              -u ${{ github.actor }} \
              --password-stdin

          # 4) 이미지 Pull & Compose Up
          docker compose pull
          docker compose up -d --no-build
