# .github/workflows/deploy.yml
name: Deploy to Azure VM
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 배포용 레포(Compose 파일 등) 체크아웃
      - name: Checkout deploy repo
        uses: actions/checkout@v4
        with:
          path: deploy

      # 2) 프론트엔드 레포 체크아웃
      - name: Checkout frontend repo
        uses: actions/checkout@v4
        with:
          repository: hc-organizations/todo-frontend
          path: deploy/todo-frontend
          token: ${{ secrets.GHCR_PAT }}

      # 3) 백엔드 레포 체크아웃
      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: hc-organizations/todo-backend
          path: deploy/todo-backend
          token: ${{ secrets.GHCR_PAT }}

      # 4) GHCR 로그인 (Runner 측)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 5) 프론트엔드 이미지 빌드·푸시
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: deploy/todo-frontend
          push: true
          tags: |
            ghcr.io/hc-organizations/todo-frontend:latest
            ghcr.io/hc-organizations/todo-frontend:${{ github.sha }}

      # 6) 백엔드 이미지 빌드·푸시
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: deploy/todo-backend
          push: true
          tags: |
            ghcr.io/hc-organizations/todo-backend:latest
            ghcr.io/hc-organizations/todo-backend:${{ github.sha }}

      # 7) SCP로 deploy/ 폴더 전체를 VM에 복사
      - name: Copy deploy folder to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: deploy/
          target: ~/deploy

      # 8) SSH로 VM에서 배포 실행
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: |
            GHCR_PAT=${{ secrets.GHCR_PAT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          script: |
            # non‑TTY GHCR login
            echo "$GHCR_PAT" \
              | docker login ghcr.io \
                  -u "${{ github.actor }}" \
                  --password-stdin

            # deploy 디렉터리로 이동
            cd ~/deploy

            # .env 파일 생성
            cat > .env <<EOF
            NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
            DB_NAME=$DB_NAME
            DB_USER=$DB_USER
            DB_PASSWORD=$DB_PASSWORD
            EOF

            # Pull & 컨테이너 재시작
            docker compose pull
            docker compose up -d --no-build
